// TODO -> DELETAR IMAGENS SEM RECARREGAR PAGINA + ATUALIZAR PREVIEW QUANDO ADICIONAR IMAGEM
// TODO -> FUNCAO LOGIN
// TODO -> FUNCAO DO FILTRO
// TODO -> LAYOUT FINAL RESPONSIVO
// TODO -> DEPLOY VERCEL