// TODO -> DELETAR IMAGENS SEM RECARREGAR PAGINA + ATUALIZAR PREVIEW QUANDO ADICIONAR IMAGEM
// TODO -> PREENCHER STATUS DO IMÓVEL QUANDO SELECIONAR EM ATUALIZAR

// TODO -> FUNCAO LOGIN
// TODO -> FUNCAO DO FILTRO
// TODO -> LAYOUT FINAL RESPONSIVO